services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: blogbot-postgres
    environment:
      POSTGRES_DB: blogbot_ia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  ollama:
    image: ollama/ollama:latest
    container_name: blogbot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  postgres_data:
  ollama_data:
